"""BriefAgent — LLM-powered intelligence briefing writer.

Produces a BLUF (Bottom Line Up Front) formatted markdown brief —
a format borrowed from military intelligence reporting:

    1. BLUF — one sentence verdict.
    2. Key facts table.
    3. Threat & opportunity summary.
    4. Indicators observed.
    5. Assessment confidence + caveats.

The BriefAgent never recommends buying or selling.
"""

from __future__ import annotations

import json

from ..llm_client import Gateway
from ..models import ChainIntel, IntelBrief, ThreatAssessment, TokenTarget


_SYSTEM = (
    "You are a crypto intelligence briefing officer.  You write in BLUF "
    "(Bottom Line Up Front) format: lead with the verdict, then evidence. "
    "Your tone is clinical and evidence-led.  You NEVER recommend buying "
    "or selling.  Output clean markdown."
)

_SKELETON = """# INTEL BRIEF — {ticker}

**Network:** {network} | **Contract:** `{contract}`
**Signal:** {signal} | **Threat:** {threat}/100 | **Opportunity:** {opp}/100
**Confidence:** {conf}%

---

## BLUF
<one-sentence bottom line summarising the signal and biggest unknown>

## Key Facts
| Metric | Value |
|--------|-------|
| Pool liquidity | ${liq} |
| 24 h volume | ${vol} |
| FDV | ${fdv} |
| Pool age | {age} |
| Source verified | {verified} |

## Threat & Opportunity
{reasoning}

## Indicators
{indicator_block}

## Caveats
<one sentence on what data is missing or unreliable>

---
_Classification: UNCLASSIFIED — auto-generated by crypto-intel._
"""


class BriefAgent:
    TAG = "brief"

    def __init__(self, gw: Gateway) -> None:
        self.gw = gw

    async def compose(
        self,
        target: TokenTarget,
        chain_intel: ChainIntel,
        assessment: ThreatAssessment,
    ) -> IntelBrief:
        skeleton = _fill_skeleton(target, chain_intel, assessment)
        prompt = (
            "Complete the markdown brief below.  Replace every `<...>` "
            "placeholder with real content based ONLY on the DATA provided.  "
            "Do NOT invent numbers — write 'n/a' for unknowns.\n\n"
            f"SKELETON:\n{skeleton}\n\n"
            "DATA:\n"
            + json.dumps(
                {
                    "target": target.model_dump(mode="json"),
                    "chain_intel": chain_intel.model_dump(mode="json"),
                    "assessment": assessment.model_dump(mode="json"),
                },
                indent=2,
                default=str,
            )
        )
        ref = f"{target.network}:{target.contract}"
        md = await self.gw.ask(
            messages=[
                {"role": "system", "content": _SYSTEM},
                {"role": "user", "content": prompt},
            ],
            temperature=0.3,
            max_tokens=2400,
            tag=self.TAG,
            ref=ref,
        )
        return IntelBrief(
            target=target,
            chain_intel=chain_intel,
            assessment=assessment,
            briefing_md=md.strip(),
        )


# ── helpers ──────────────────────────────────────────────────────────

def _usd(v: float | None) -> str:
    if v is None:
        return "n/a"
    if v >= 1_000_000:
        return f"{v / 1_000_000:.2f}M"
    if v >= 1_000:
        return f"{v / 1_000:.1f}K"
    return f"{v:.2f}"


def _fill_skeleton(
    t: TokenTarget, ci: ChainIntel, a: ThreatAssessment
) -> str:
    indicators = "\n".join(f"- `{i}`" for i in a.indicators) or "- (none)"
    verified = (
        "yes" if ci.source_public else ("no" if ci.source_public is False else "n/a")
    )
    return _SKELETON.format(
        ticker=t.ticker,
        network=t.network,
        contract=t.contract or "n/a",
        signal=a.signal.value,
        threat=a.threat_score,
        opp=a.opportunity_score,
        conf=a.confidence_pct,
        liq=_usd(t.pool_liquidity),
        vol=_usd(t.day_volume),
        fdv=_usd(t.fully_diluted_val),
        age=t.pool_born.isoformat() if t.pool_born else "n/a",
        verified=verified,
        reasoning=a.reasoning,
        indicator_block=indicators,
    )
