"""Summary renderer — generates daily intelligence summaries from the Ledger."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from .ledger import Ledger


def render_summary(ledger: Ledger, *, model: Optional[str] = None) -> str:
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d UTC")
    tok_all = ledger.total_tokens()
    tok_today = ledger.tokens_today()
    missions = ledger.mission_count()
    tags = ledger.by_tag()
    heatmap = ledger.daily_heatmap(days=7)
    recent = ledger.recent_missions(n=10)

    lines: list[str] = [
        "# Daily Intelligence Summary",
        f"**Date:** {today}",
    ]
    if model:
        lines.append(f"**Model:** `{model}`")
    lines += [
        "",
        "## Token Consumption",
        "",
        f"- **Today:** {tok_today:,} tokens",
        f"- **Lifetime:** {tok_all:,} tokens",
        f"- **Missions completed:** {missions:,}",
        "",
    ]

    if tags:
        lines += ["## By Agent", "", "| Agent | Calls | Tokens |", "|---|---:|---:|"]
        for tag, calls, tokens in tags:
            lines.append(f"| `{tag}` | {calls:,} | {tokens:,} |")
        lines.append("")

    if heatmap:
        lines += ["## 7-Day Heatmap", "", "| Date | Calls | Tokens |", "|---|---:|---:|"]
        for day, calls, tokens in heatmap:
            lines.append(f"| {day} | {calls:,} | {tokens:,} |")
        lines.append("")

    if recent:
        lines += [
            "## Recent Missions",
            "",
            "| Time (UTC) | Ticker | Network | Signal | Threat | Tokens | Latency |",
            "|---|---|---|---|---:|---:|---:|",
        ]
        for m in recent:
            ts = (m.get("ts") or "")[:19].replace("T", " ")
            lines.append(
                f"| {ts} "
                f"| {m.get('ticker') or '?'} "
                f"| {m.get('network') or '?'} "
                f"| {m.get('signal') or '?'} "
                f"| {m.get('threat') or '?'} "
                f"| {int(m.get('tokens_used') or 0):,} "
                f"| {int(m.get('ms') or 0) / 1000:.1f}s |"
            )
        lines.append("")

    lines += ["---", "", "_Generated by `cri summary`._"]
    return "\n".join(lines)


def write_summary(ledger: Ledger, out_dir: Path, *, model: Optional[str] = None) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    text = render_summary(ledger, model=model)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    path = out_dir / f"daily_{today}.md"
    path.write_text(text, encoding="utf-8")
    return path
